spring.application.name=suyu
spring.datasource.url=jdbc:h2:mem:glowcaredb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=8050@Pra
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
server.port=9090