spring.application.name=suyu
spring.datasource.url=jdbc:h2:mem:glowcaredb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=8050@Pra
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
server.port=9090
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=glowcare021@gmail.com
spring.mail.password=rlsi xlqj ykce dsno
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.debug=true

# Multipart File Upload Limits
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

