spring.application.name=suyu
# H2 Database (Active: Persistent File)
spring.datasource.url=jdbc:h2:file:./data/suyudb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# MySQL Database (Commented out)
# spring.datasource.url=jdbc:mysql://localhost:3306/suyu_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.datasource.username=root
# spring.datasource.password=root
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=9090
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=glowcare021@gmail.com
spring.mail.password=rlsi xlqj ykce dsno
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.debug=true

# Multipart File Upload Limits
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
